language: ruby
dist: xenial
sudo: false
cache: bundler
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

script: bundle exec rspec -f progress --force-color --color --tty

gemfile:
  - gemfiles/cucumber1.gemfile
  - gemfiles/cucumber2.gemfile
  - gemfiles/cucumber3.gemfile
  - gemfiles/cucumber4.gemfile
